preload:
  keep_unsorted: False
  verbose: True
chop_merge:
  bin_size: 0.010
  window_len: 60
  overlap: 20
dynamics_analysis:
  num_dims: 10
  bin_size: 0.030
  keep_unsorted: False
  verbose: True
inspection:
  bin_size: 0.010
  keep_unsorted: True
  verbose: True
context_analysis:
  bin_size: 0.010
  keep_unsorted: True
  verbose: True
submovement_decomposition:
  bin_size: 0.010
  keep_unsorted: True
  verbose: True